image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t automation-test docker/
    - docker run --privileged automation-test

#image: kaiwinter/docker-java8-maven
#stages:
#  - test
#test:
# script: "mvn clean test"